services:
  - type: web
    name: CoWatch
    env: node
    buildCommand: cd "The Magic" && npm install
    startCommand: cd "The Magic" && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000